//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace HCISSepas.billpatientsrv {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BillPatientServiceSoap", Namespace="http://sepas.behdasht.gov.ir/")]
    public partial class BillPatientService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private HeaderMessageVO headerMessageVOValueField;
        
        private System.Threading.SendOrPostCallback SavePatientBillOperationCompleted;
        
        private System.Threading.SendOrPostCallback SavePatientBillSecureOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BillPatientService() {
            this.Url = global::HCISSepas.Properties.Settings.Default.HCISSepas_billpatientsrv_BillPatientService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public HeaderMessageVO HeaderMessageVOValue {
            get {
                return this.headerMessageVOValueField;
            }
            set {
                this.headerMessageVOValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SavePatientBillCompletedEventHandler SavePatientBillCompleted;
        
        /// <remarks/>
        public event SavePatientBillSecureCompletedEventHandler SavePatientBillSecureCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("HeaderMessageVOValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sepas.behdasht.gov.ir/SavePatientBill", RequestNamespace="http://sepas.behdasht.gov.ir/", ResponseNamespace="http://sepas.behdasht.gov.ir/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultVO SavePatientBill(PatientBillMessageVO PatientBill) {
            object[] results = this.Invoke("SavePatientBill", new object[] {
                        PatientBill});
            return ((ResultVO)(results[0]));
        }
        
        /// <remarks/>
        public void SavePatientBillAsync(PatientBillMessageVO PatientBill) {
            this.SavePatientBillAsync(PatientBill, null);
        }
        
        /// <remarks/>
        public void SavePatientBillAsync(PatientBillMessageVO PatientBill, object userState) {
            if ((this.SavePatientBillOperationCompleted == null)) {
                this.SavePatientBillOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSavePatientBillOperationCompleted);
            }
            this.InvokeAsync("SavePatientBill", new object[] {
                        PatientBill}, this.SavePatientBillOperationCompleted, userState);
        }
        
        private void OnSavePatientBillOperationCompleted(object arg) {
            if ((this.SavePatientBillCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SavePatientBillCompleted(this, new SavePatientBillCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("HeaderMessageVOValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sepas.behdasht.gov.ir/SavePatientBillSecure", RequestNamespace="http://sepas.behdasht.gov.ir/", ResponseNamespace="http://sepas.behdasht.gov.ir/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultVO SavePatientBillSecure([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] data) {
            object[] results = this.Invoke("SavePatientBillSecure", new object[] {
                        data});
            return ((ResultVO)(results[0]));
        }
        
        /// <remarks/>
        public void SavePatientBillSecureAsync(byte[] data) {
            this.SavePatientBillSecureAsync(data, null);
        }
        
        /// <remarks/>
        public void SavePatientBillSecureAsync(byte[] data, object userState) {
            if ((this.SavePatientBillSecureOperationCompleted == null)) {
                this.SavePatientBillSecureOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSavePatientBillSecureOperationCompleted);
            }
            this.InvokeAsync("SavePatientBillSecure", new object[] {
                        data}, this.SavePatientBillSecureOperationCompleted, userState);
        }
        
        private void OnSavePatientBillSecureOperationCompleted(object arg) {
            if ((this.SavePatientBillSecureCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SavePatientBillSecureCompleted(this, new SavePatientBillSecureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thrita.behdasht.gov.ir/VM/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://sepas.behdasht.gov.ir/", IsNullable=false)]
    public partial class HeaderMessageVO : System.Web.Services.Protocols.SoapHeader {
        
        private SystemSenderVO senderField;
        
        private SystemSenderVO[] senderListField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public SystemSenderVO Sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
            }
        }
        
        /// <remarks/>
        public SystemSenderVO[] SenderList {
            get {
                return this.senderListField;
            }
            set {
                this.senderListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thrita.behdasht.gov.ir/VM/")]
    public partial class SystemSenderVO {
        
        private string systemIDField;
        
        private string locationIDField;
        
        private string ipField;
        
        private string uRLField;
        
        private SignatureVO proofField;
        
        private System.Nullable<System.DateTime> dateTimeStampField;
        
        /// <remarks/>
        public string SystemID {
            get {
                return this.systemIDField;
            }
            set {
                this.systemIDField = value;
            }
        }
        
        /// <remarks/>
        public string LocationID {
            get {
                return this.locationIDField;
            }
            set {
                this.locationIDField = value;
            }
        }
        
        /// <remarks/>
        public string IP {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
            }
        }
        
        /// <remarks/>
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
            }
        }
        
        /// <remarks/>
        public SignatureVO Proof {
            get {
                return this.proofField;
            }
            set {
                this.proofField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DateTimeStamp {
            get {
                return this.dateTimeStampField;
            }
            set {
                this.dateTimeStampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thrita.behdasht.gov.ir/VM/")]
    public partial class SignatureVO {
        
        private byte[] signatureValueField;
        
        private string signatureMethodField;
        
        private System.Nullable<System.DateTime> timeStampField;
        
        private byte[] certificateField;
        
        private string subjectDNField;
        
        private string thumbprintField;
        
        private string orderTypeField;
        
        private DO_CODED_TEXT signerRoleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] SignatureValue {
            get {
                return this.signatureValueField;
            }
            set {
                this.signatureValueField = value;
            }
        }
        
        /// <remarks/>
        public string SignatureMethod {
            get {
                return this.signatureMethodField;
            }
            set {
                this.signatureMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Certificate {
            get {
                return this.certificateField;
            }
            set {
                this.certificateField = value;
            }
        }
        
        /// <remarks/>
        public string SubjectDN {
            get {
                return this.subjectDNField;
            }
            set {
                this.subjectDNField = value;
            }
        }
        
        /// <remarks/>
        public string Thumbprint {
            get {
                return this.thumbprintField;
            }
            set {
                this.thumbprintField = value;
            }
        }
        
        /// <remarks/>
        public string OrderType {
            get {
                return this.orderTypeField;
            }
            set {
                this.orderTypeField = value;
            }
        }
        
        /// <remarks/>
        public DO_CODED_TEXT SignerRole {
            get {
                return this.signerRoleField;
            }
            set {
                this.signerRoleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thrita.behdasht.gov.ir/VM/")]
    public partial class DO_CODED_TEXT {
        
        private string valueField;
        
        private string terminology_idField;
        
        private string coded_stringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Terminology_id {
            get {
                return this.terminology_idField;
            }
            set {
                this.terminology_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Coded_string {
            get {
                return this.coded_stringField;
            }
            set {
                this.coded_stringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thrita.behdasht.gov.ir/VM/")]
    public partial class ResultVO {
        
        private string messageUIDField;
        
        private string errorMessageField;
        
        private string compositionUIDField;
        
        private string patientUIDField;
        
        /// <remarks/>
        public string MessageUID {
            get {
                return this.messageUIDField;
            }
            set {
                this.messageUIDField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public string CompositionUID {
            get {
                return this.compositionUIDField;
            }
            set {
                this.compositionUIDField = value;
            }
        }
        
        /// <remarks/>
        public string patientUID {
            get {
                return this.patientUIDField;
            }
            set {
                this.patientUIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thrita.behdasht.gov.ir/VM/")]
    public partial class DO_ORDINAL {
        
        private DO_CODED_TEXT symbolField;
        
        private System.Nullable<int> valueField;
        
        /// <remarks/>
        public DO_CODED_TEXT Symbol {
            get {
                return this.symbolField;
            }
            set {
                this.symbolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thrita.behdasht.gov.ir/VM/")]
    public partial class DiagnosisVO {
        
        private DO_CODED_TEXT diagnosisField;
        
        private string commentField;
        
        private DO_CODED_TEXT statusField;
        
        private DO_DATE diagnosisDateField;
        
        private DO_TIME diagnosisTimeField;
        
        private DO_ORDINAL severityField;
        
        /// <remarks/>
        public DO_CODED_TEXT Diagnosis {
            get {
                return this.diagnosisField;
            }
            set {
                this.diagnosisField = value;
            }
        }
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        public DO_CODED_TEXT Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public DO_DATE DiagnosisDate {
            get {
                return this.diagnosisDateField;
            }
            set {
                this.diagnosisDateField = value;
            }
        }
        
        /// <remarks/>
        public DO_TIME DiagnosisTime {
            get {
                return this.diagnosisTimeField;
            }
            set {
                this.diagnosisTimeField = value;
            }
        }
        
        /// <remarks/>
        public DO_ORDINAL Severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thrita.behdasht.gov.ir/VM/")]
    public partial class DO_DATE {
        
        private System.Nullable<int> yearField;
        
        private System.Nullable<int> monthField;
        
        private System.Nullable<int> dayField;
        
        private string iSOStringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Month {
            get {
                return this.monthField;
            }
            set {
                this.monthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Day {
            get {
                return this.dayField;
            }
            set {
                this.dayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ISOString {
            get {
                return this.iSOStringField;
            }
            set {
                this.iSOStringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thrita.behdasht.gov.ir/VM/")]
    public partial class DO_TIME {
        
        private string iSOStringField;
        
        private System.Nullable<int> hourField;
        
        private System.Nullable<int> minuteField;
        
        private System.Nullable<int> secondField;
        
        /// <remarks/>
        public string ISOString {
            get {
                return this.iSOStringField;
            }
            set {
                this.iSOStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Hour {
            get {
                return this.hourField;
            }
            set {
                this.hourField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Minute {
            get {
                return this.minuteField;
            }
            set {
                this.minuteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Second {
            get {
                return this.secondField;
            }
            set {
                this.secondField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thrita.behdasht.gov.ir/VM/")]
    public partial class CauseVO {
        
        private DO_CODED_TEXT causeField;
        
        private DO_CODED_TEXT statusField;
        
        /// <remarks/>
        public DO_CODED_TEXT Cause {
            get {
                return this.causeField;
            }
            set {
                this.causeField = value;
            }
        }
        
        /// <remarks/>
        public DO_CODED_TEXT Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thrita.behdasht.gov.ir/VM/")]
    public partial class BasicDeathDetailsVO {
        
        private DO_DATE deathDateField;
        
        private DO_TIME deathTimeField;
        
        private DO_CODED_TEXT deathLocationField;
        
        private DO_CODED_TEXT hospitalWardField;
        
        private CauseVO[] causeField;
        
        /// <remarks/>
        public DO_DATE DeathDate {
            get {
                return this.deathDateField;
            }
            set {
                this.deathDateField = value;
            }
        }
        
        /// <remarks/>
        public DO_TIME DeathTime {
            get {
                return this.deathTimeField;
            }
            set {
                this.deathTimeField = value;
            }
        }
        
        /// <remarks/>
        public DO_CODED_TEXT DeathLocation {
            get {
                return this.deathLocationField;
            }
            set {
                this.deathLocationField = value;
            }
        }
        
        /// <remarks/>
        public DO_CODED_TEXT HospitalWard {
            get {
                return this.hospitalWardField;
            }
            set {
                this.hospitalWardField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public CauseVO[] Cause {
            get {
                return this.causeField;
            }
            set {
                this.causeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thrita.behdasht.gov.ir/VM/")]
    public partial class InsuranceVO {
        
        private DO_QUANTITY insuranceContributionField;
        
        private QuantitiesVO[] insuranceOtherCostsField;
        
        private DO_CODED_TEXT insurerField;
        
        private DO_CODED_TEXT insuranceBoxField;
        
        private string insuranceBookletSerialNumberField;
        
        private DO_DATE insuranceExpirationDateField;
        
        private string insuredNumberField;
        
        private DO_IDENTIFIER sHEBADField;
        
        /// <remarks/>
        public DO_QUANTITY InsuranceContribution {
            get {
                return this.insuranceContributionField;
            }
            set {
                this.insuranceContributionField = value;
            }
        }
        
        /// <remarks/>
        public QuantitiesVO[] InsuranceOtherCosts {
            get {
                return this.insuranceOtherCostsField;
            }
            set {
                this.insuranceOtherCostsField = value;
            }
        }
        
        /// <remarks/>
        public DO_CODED_TEXT Insurer {
            get {
                return this.insurerField;
            }
            set {
                this.insurerField = value;
            }
        }
        
        /// <remarks/>
        public DO_CODED_TEXT InsuranceBox {
            get {
                return this.insuranceBoxField;
            }
            set {
                this.insuranceBoxField = value;
            }
        }
        
        /// <remarks/>
        public string InsuranceBookletSerialNumber {
            get {
                return this.insuranceBookletSerialNumberField;
            }
            set {
                this.insuranceBookletSerialNumberField = value;
            }
        }
        
        /// <remarks/>
        public DO_DATE InsuranceExpirationDate {
            get {
                return this.insuranceExpirationDateField;
            }
            set {
                this.insuranceExpirationDateField = value;
            }
        }
        
        /// <remarks/>
        public string InsuredNumber {
            get {
                return this.insuredNumberField;
            }
            set {
                this.insuredNumberField = value;
            }
        }
        
        /// <remarks/>
        public DO_IDENTIFIER SHEBAD {
            get {
                return this.sHEBADField;
            }
            set {
                this.sHEBADField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thrita.behdasht.gov.ir/VM/")]
    public partial class DO_QUANTITY {
        
        private System.Nullable<double> magnitudeField;
        
        private string unitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Magnitude {
            get {
                return this.magnitudeField;
            }
            set {
                this.magnitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thrita.behdasht.gov.ir/VM/")]
    public partial class QuantitiesVO {
        
        private DO_CODED_TEXT nameField;
        
        private DO_QUANTITY valueField;
        
        /// <remarks/>
        public DO_CODED_TEXT Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public DO_QUANTITY Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thrita.behdasht.gov.ir/VM/")]
    public partial class DO_IDENTIFIER {
        
        private string issuerField;
        
        private string assignerField;
        
        private string idField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Issuer {
            get {
                return this.issuerField;
            }
            set {
                this.issuerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Assigner {
            get {
                return this.assignerField;
            }
            set {
                this.assignerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thrita.behdasht.gov.ir/VM/")]
    public partial class RelativeCostVO {
        
        private System.Nullable<double> kValueField;
        
        private DO_CODED_TEXT kTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> KValue {
            get {
                return this.kValueField;
            }
            set {
                this.kValueField = value;
            }
        }
        
        /// <remarks/>
        public DO_CODED_TEXT KType {
            get {
                return this.kTypeField;
            }
            set {
                this.kTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thrita.behdasht.gov.ir/VM/")]
    public partial class ServiceDetailsVO {
        
        private OrganizationVO extraLocationField;
        
        private ServiceDetailsVO[] relatedServiceField;
        
        private string pKIDField;
        
        private RelativeCostVO[] relativeCostField;
        
        private QuantitiesVO[] otherCostsField;
        
        private DO_QUANTITY basicInsuranceContributionField;
        
        private string bedField;
        
        private DO_QUANTITY serviceCountField;
        
        private DO_QUANTITY patientContributionField;
        
        private string roomField;
        
        private DO_CODED_TEXT serviceField;
        
        private DO_DATE startDateField;
        
        private DO_TIME startTimeField;
        
        private DO_DATE endDateField;
        
        private DO_TIME endTimeField;
        
        private DO_CODED_TEXT serviceTypeField;
        
        private DO_QUANTITY totalChargeField;
        
        private DO_CODED_TEXT wardTypeField;
        
        private string wardNameField;
        
        private HealthcareProviderVO serviceProviderField;
        
        /// <remarks/>
        public OrganizationVO ExtraLocation {
            get {
                return this.extraLocationField;
            }
            set {
                this.extraLocationField = value;
            }
        }
        
        /// <remarks/>
        public ServiceDetailsVO[] RelatedService {
            get {
                return this.relatedServiceField;
            }
            set {
                this.relatedServiceField = value;
            }
        }
        
        /// <remarks/>
        public string PKID {
            get {
                return this.pKIDField;
            }
            set {
                this.pKIDField = value;
            }
        }
        
        /// <remarks/>
        public RelativeCostVO[] RelativeCost {
            get {
                return this.relativeCostField;
            }
            set {
                this.relativeCostField = value;
            }
        }
        
        /// <remarks/>
        public QuantitiesVO[] OtherCosts {
            get {
                return this.otherCostsField;
            }
            set {
                this.otherCostsField = value;
            }
        }
        
        /// <remarks/>
        public DO_QUANTITY BasicInsuranceContribution {
            get {
                return this.basicInsuranceContributionField;
            }
            set {
                this.basicInsuranceContributionField = value;
            }
        }
        
        /// <remarks/>
        public string Bed {
            get {
                return this.bedField;
            }
            set {
                this.bedField = value;
            }
        }
        
        /// <remarks/>
        public DO_QUANTITY ServiceCount {
            get {
                return this.serviceCountField;
            }
            set {
                this.serviceCountField = value;
            }
        }
        
        /// <remarks/>
        public DO_QUANTITY PatientContribution {
            get {
                return this.patientContributionField;
            }
            set {
                this.patientContributionField = value;
            }
        }
        
        /// <remarks/>
        public string Room {
            get {
                return this.roomField;
            }
            set {
                this.roomField = value;
            }
        }
        
        /// <remarks/>
        public DO_CODED_TEXT Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
            }
        }
        
        /// <remarks/>
        public DO_DATE StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        public DO_TIME StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        public DO_DATE EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        public DO_TIME EndTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
            }
        }
        
        /// <remarks/>
        public DO_CODED_TEXT ServiceType {
            get {
                return this.serviceTypeField;
            }
            set {
                this.serviceTypeField = value;
            }
        }
        
        /// <remarks/>
        public DO_QUANTITY TotalCharge {
            get {
                return this.totalChargeField;
            }
            set {
                this.totalChargeField = value;
            }
        }
        
        /// <remarks/>
        public DO_CODED_TEXT WardType {
            get {
                return this.wardTypeField;
            }
            set {
                this.wardTypeField = value;
            }
        }
        
        /// <remarks/>
        public string WardName {
            get {
                return this.wardNameField;
            }
            set {
                this.wardNameField = value;
            }
        }
        
        /// <remarks/>
        public HealthcareProviderVO ServiceProvider {
            get {
                return this.serviceProviderField;
            }
            set {
                this.serviceProviderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thrita.behdasht.gov.ir/VM/")]
    public partial class OrganizationVO {
        
        private string nameField;
        
        private DO_IDENTIFIER idField;
        
        private DO_CODED_TEXT typeField;
        
        private HighLevelAreaVO locationField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public DO_IDENTIFIER ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public DO_CODED_TEXT Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public HighLevelAreaVO Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thrita.behdasht.gov.ir/VM/")]
    public partial class HighLevelAreaVO {
        
        private DO_CODED_TEXT nationalAreaCodeField;
        
        private DO_CODED_TEXT countryField;
        
        private DO_CODED_TEXT provinceField;
        
        private DO_CODED_TEXT cityField;
        
        private DO_CODED_TEXT townField;
        
        private DO_CODED_TEXT districtField;
        
        private DO_CODED_TEXT ruralAreaField;
        
        private DO_CODED_TEXT villageField;
        
        /// <remarks/>
        public DO_CODED_TEXT NationalAreaCode {
            get {
                return this.nationalAreaCodeField;
            }
            set {
                this.nationalAreaCodeField = value;
            }
        }
        
        /// <remarks/>
        public DO_CODED_TEXT Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public DO_CODED_TEXT Province {
            get {
                return this.provinceField;
            }
            set {
                this.provinceField = value;
            }
        }
        
        /// <remarks/>
        public DO_CODED_TEXT City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public DO_CODED_TEXT Town {
            get {
                return this.townField;
            }
            set {
                this.townField = value;
            }
        }
        
        /// <remarks/>
        public DO_CODED_TEXT District {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
            }
        }
        
        /// <remarks/>
        public DO_CODED_TEXT RuralArea {
            get {
                return this.ruralAreaField;
            }
            set {
                this.ruralAreaField = value;
            }
        }
        
        /// <remarks/>
        public DO_CODED_TEXT Village {
            get {
                return this.villageField;
            }
            set {
                this.villageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thrita.behdasht.gov.ir/VM/")]
    public partial class HealthcareProviderVO {
        
        private DO_CODED_TEXT specialtyField;
        
        private DO_IDENTIFIER identifierField;
        
        private DO_CODED_TEXT roleField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string fullNameField;
        
        /// <remarks/>
        public DO_CODED_TEXT Specialty {
            get {
                return this.specialtyField;
            }
            set {
                this.specialtyField = value;
            }
        }
        
        /// <remarks/>
        public DO_IDENTIFIER Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        public DO_CODED_TEXT Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thrita.behdasht.gov.ir/VM/")]
    public partial class ServiceGroupRowVO {
        
        private DO_QUANTITY patientContributionField;
        
        private QuantitiesVO[] otherCostsField;
        
        private DO_QUANTITY basicInsuranceContributionField;
        
        private DO_QUANTITY serviceCountField;
        
        private DO_CODED_TEXT serviceTypeField;
        
        private DO_QUANTITY totalChargeField;
        
        /// <remarks/>
        public DO_QUANTITY PatientContribution {
            get {
                return this.patientContributionField;
            }
            set {
                this.patientContributionField = value;
            }
        }
        
        /// <remarks/>
        public QuantitiesVO[] OtherCosts {
            get {
                return this.otherCostsField;
            }
            set {
                this.otherCostsField = value;
            }
        }
        
        /// <remarks/>
        public DO_QUANTITY BasicInsuranceContribution {
            get {
                return this.basicInsuranceContributionField;
            }
            set {
                this.basicInsuranceContributionField = value;
            }
        }
        
        /// <remarks/>
        public DO_QUANTITY ServiceCount {
            get {
                return this.serviceCountField;
            }
            set {
                this.serviceCountField = value;
            }
        }
        
        /// <remarks/>
        public DO_CODED_TEXT ServiceType {
            get {
                return this.serviceTypeField;
            }
            set {
                this.serviceTypeField = value;
            }
        }
        
        /// <remarks/>
        public DO_QUANTITY TotalCharge {
            get {
                return this.totalChargeField;
            }
            set {
                this.totalChargeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thrita.behdasht.gov.ir/VM/")]
    public partial class BillSummaryVO {
        
        private QuantitiesVO[] totalOtherCostsField;
        
        private DO_CODED_TEXT insurerField;
        
        private DO_CODED_TEXT insurerBoxField;
        
        private DO_QUANTITY totalBasicInsuranceContributionField;
        
        private int hospitalAccreditationField;
        
        private DO_CODED_TEXT medicalRecordTypeField;
        
        private DO_CODED_TEXT globalPackageField;
        
        private DO_QUANTITY totalPatientContributionField;
        
        private DO_QUANTITY totalChargeField;
        
        private ServiceGroupRowVO[] serviceGroupRowField;
        
        /// <remarks/>
        public QuantitiesVO[] TotalOtherCosts {
            get {
                return this.totalOtherCostsField;
            }
            set {
                this.totalOtherCostsField = value;
            }
        }
        
        /// <remarks/>
        public DO_CODED_TEXT Insurer {
            get {
                return this.insurerField;
            }
            set {
                this.insurerField = value;
            }
        }
        
        /// <remarks/>
        public DO_CODED_TEXT InsurerBox {
            get {
                return this.insurerBoxField;
            }
            set {
                this.insurerBoxField = value;
            }
        }
        
        /// <remarks/>
        public DO_QUANTITY TotalBasicInsuranceContribution {
            get {
                return this.totalBasicInsuranceContributionField;
            }
            set {
                this.totalBasicInsuranceContributionField = value;
            }
        }
        
        /// <remarks/>
        public int HospitalAccreditation {
            get {
                return this.hospitalAccreditationField;
            }
            set {
                this.hospitalAccreditationField = value;
            }
        }
        
        /// <remarks/>
        public DO_CODED_TEXT MedicalRecordType {
            get {
                return this.medicalRecordTypeField;
            }
            set {
                this.medicalRecordTypeField = value;
            }
        }
        
        /// <remarks/>
        public DO_CODED_TEXT GlobalPackage {
            get {
                return this.globalPackageField;
            }
            set {
                this.globalPackageField = value;
            }
        }
        
        /// <remarks/>
        public DO_QUANTITY TotalPatientContribution {
            get {
                return this.totalPatientContributionField;
            }
            set {
                this.totalPatientContributionField = value;
            }
        }
        
        /// <remarks/>
        public DO_QUANTITY TotalCharge {
            get {
                return this.totalChargeField;
            }
            set {
                this.totalChargeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ServiceGroupRowVO[] ServiceGroupRow {
            get {
                return this.serviceGroupRowField;
            }
            set {
                this.serviceGroupRowField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thrita.behdasht.gov.ir/VM/")]
    public partial class DischargeVO {
        
        private DO_TIME dischargeTimeField;
        
        private DO_DATE dischargeDateField;
        
        private DO_CODED_TEXT conditionOnDischargeField;
        
        /// <remarks/>
        public DO_TIME DischargeTime {
            get {
                return this.dischargeTimeField;
            }
            set {
                this.dischargeTimeField = value;
            }
        }
        
        /// <remarks/>
        public DO_DATE DischargeDate {
            get {
                return this.dischargeDateField;
            }
            set {
                this.dischargeDateField = value;
            }
        }
        
        /// <remarks/>
        public DO_CODED_TEXT ConditionOnDischarge {
            get {
                return this.conditionOnDischargeField;
            }
            set {
                this.conditionOnDischargeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thrita.behdasht.gov.ir/VM/")]
    public partial class HospitalWardVO {
        
        private string nameField;
        
        private DO_CODED_TEXT typeField;
        
        private string roomField;
        
        private string bedField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public DO_CODED_TEXT Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Room {
            get {
                return this.roomField;
            }
            set {
                this.roomField = value;
            }
        }
        
        /// <remarks/>
        public string Bed {
            get {
                return this.bedField;
            }
            set {
                this.bedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thrita.behdasht.gov.ir/VM/")]
    public partial class DateTimePointVO {
        
        private DO_CODED_TEXT pointField;
        
        private DO_DATE pointDateField;
        
        private DO_TIME pointTimeField;
        
        /// <remarks/>
        public DO_CODED_TEXT Point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
        
        /// <remarks/>
        public DO_DATE PointDate {
            get {
                return this.pointDateField;
            }
            set {
                this.pointDateField = value;
            }
        }
        
        /// <remarks/>
        public DO_TIME PointTime {
            get {
                return this.pointTimeField;
            }
            set {
                this.pointTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thrita.behdasht.gov.ir/VM/")]
    public partial class AdmissionVO {
        
        private DO_IDENTIFIER eMSIDField;
        
        private DateTimePointVO[] otherDateTimeField;
        
        private DO_DATE admissionDateField;
        
        private DO_TIME admissionTimeField;
        
        private DO_CODED_TEXT admissionTypeField;
        
        private string medicalRecordNumberField;
        
        private OrganizationVO instituteField;
        
        private DO_CODED_TEXT reasonForEncounterField;
        
        private HealthcareProviderVO admittingDoctorField;
        
        private HealthcareProviderVO referringDoctorField;
        
        private HealthcareProviderVO attendingDoctorField;
        
        private HospitalWardVO admissionWardField;
        
        /// <remarks/>
        public DO_IDENTIFIER EMSID {
            get {
                return this.eMSIDField;
            }
            set {
                this.eMSIDField = value;
            }
        }
        
        /// <remarks/>
        public DateTimePointVO[] OtherDateTime {
            get {
                return this.otherDateTimeField;
            }
            set {
                this.otherDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public DO_DATE AdmissionDate {
            get {
                return this.admissionDateField;
            }
            set {
                this.admissionDateField = value;
            }
        }
        
        /// <remarks/>
        public DO_TIME AdmissionTime {
            get {
                return this.admissionTimeField;
            }
            set {
                this.admissionTimeField = value;
            }
        }
        
        /// <remarks/>
        public DO_CODED_TEXT AdmissionType {
            get {
                return this.admissionTypeField;
            }
            set {
                this.admissionTypeField = value;
            }
        }
        
        /// <remarks/>
        public string MedicalRecordNumber {
            get {
                return this.medicalRecordNumberField;
            }
            set {
                this.medicalRecordNumberField = value;
            }
        }
        
        /// <remarks/>
        public OrganizationVO Institute {
            get {
                return this.instituteField;
            }
            set {
                this.instituteField = value;
            }
        }
        
        /// <remarks/>
        public DO_CODED_TEXT ReasonForEncounter {
            get {
                return this.reasonForEncounterField;
            }
            set {
                this.reasonForEncounterField = value;
            }
        }
        
        /// <remarks/>
        public HealthcareProviderVO AdmittingDoctor {
            get {
                return this.admittingDoctorField;
            }
            set {
                this.admittingDoctorField = value;
            }
        }
        
        /// <remarks/>
        public HealthcareProviderVO ReferringDoctor {
            get {
                return this.referringDoctorField;
            }
            set {
                this.referringDoctorField = value;
            }
        }
        
        /// <remarks/>
        public HealthcareProviderVO AttendingDoctor {
            get {
                return this.attendingDoctorField;
            }
            set {
                this.attendingDoctorField = value;
            }
        }
        
        /// <remarks/>
        public HospitalWardVO AdmissionWard {
            get {
                return this.admissionWardField;
            }
            set {
                this.admissionWardField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thrita.behdasht.gov.ir/VM/")]
    public partial class BillPatientCompositionVO {
        
        private AdmissionVO admissionField;
        
        private DischargeVO dischargeField;
        
        private BillSummaryVO billSummaryField;
        
        private ServiceDetailsVO[] billServicesField;
        
        private InsuranceVO[] insuranceField;
        
        private BasicDeathDetailsVO deathField;
        
        private DiagnosisVO[] diagnosisField;
        
        /// <remarks/>
        public AdmissionVO Admission {
            get {
                return this.admissionField;
            }
            set {
                this.admissionField = value;
            }
        }
        
        /// <remarks/>
        public DischargeVO Discharge {
            get {
                return this.dischargeField;
            }
            set {
                this.dischargeField = value;
            }
        }
        
        /// <remarks/>
        public BillSummaryVO BillSummary {
            get {
                return this.billSummaryField;
            }
            set {
                this.billSummaryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ServiceDetailsVO[] BillServices {
            get {
                return this.billServicesField;
            }
            set {
                this.billServicesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public InsuranceVO[] Insurance {
            get {
                return this.insuranceField;
            }
            set {
                this.insuranceField = value;
            }
        }
        
        /// <remarks/>
        public BasicDeathDetailsVO Death {
            get {
                return this.deathField;
            }
            set {
                this.deathField = value;
            }
        }
        
        /// <remarks/>
        public DiagnosisVO[] Diagnosis {
            get {
                return this.diagnosisField;
            }
            set {
                this.diagnosisField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thrita.behdasht.gov.ir/VM/")]
    public partial class ProviderInfoVO {
        
        private DO_IDENTIFIER identifierField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string fullNameField;
        
        /// <remarks/>
        public DO_IDENTIFIER Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thrita.behdasht.gov.ir/VM/")]
    public partial class MessageIdentifierVO {
        
        private DO_CODED_TEXT versionLifecycleStateField;
        
        private System.Nullable<bool> iS_QueriableField;
        
        private SignatureVO compositionSignatureField;
        
        private DO_IDENTIFIER systemIDField;
        
        private DO_IDENTIFIER healthCareFacilityIDField;
        
        private string patientUIDField;
        
        private string compositionUIDField;
        
        private ProviderInfoVO committerField;
        
        /// <remarks/>
        public DO_CODED_TEXT VersionLifecycleState {
            get {
                return this.versionLifecycleStateField;
            }
            set {
                this.versionLifecycleStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IS_Queriable {
            get {
                return this.iS_QueriableField;
            }
            set {
                this.iS_QueriableField = value;
            }
        }
        
        /// <remarks/>
        public SignatureVO CompositionSignature {
            get {
                return this.compositionSignatureField;
            }
            set {
                this.compositionSignatureField = value;
            }
        }
        
        /// <remarks/>
        public DO_IDENTIFIER SystemID {
            get {
                return this.systemIDField;
            }
            set {
                this.systemIDField = value;
            }
        }
        
        /// <remarks/>
        public DO_IDENTIFIER HealthCareFacilityID {
            get {
                return this.healthCareFacilityIDField;
            }
            set {
                this.healthCareFacilityIDField = value;
            }
        }
        
        /// <remarks/>
        public string PatientUID {
            get {
                return this.patientUIDField;
            }
            set {
                this.patientUIDField = value;
            }
        }
        
        /// <remarks/>
        public string CompositionUID {
            get {
                return this.compositionUIDField;
            }
            set {
                this.compositionUIDField = value;
            }
        }
        
        /// <remarks/>
        public ProviderInfoVO Committer {
            get {
                return this.committerField;
            }
            set {
                this.committerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thrita.behdasht.gov.ir/VM/")]
    public partial class PersonInfoVO {
        
        private DO_IDENTIFIER[] otherIdentifierField;
        
        private HighLevelAreaVO birthPlaceAreaField;
        
        private DO_CODED_TEXT religionField;
        
        private DO_CODED_TEXT maritalStatusField;
        
        private DO_CODED_TEXT nationalityField;
        
        private DO_DATE birthDateField;
        
        private DO_TIME birthTimeField;
        
        private DO_CODED_TEXT birthdateAccuracyField;
        
        private string father_FirstNameField;
        
        private string father_LastNameField;
        
        private string mother_FirstNameField;
        
        private string mother_LastNameField;
        
        private string fullNameField;
        
        private string postalCodeField;
        
        private DO_CODED_TEXT genderField;
        
        private DO_CODED_TEXT jobField;
        
        private string jobDescribtionField;
        
        private string fullAddressField;
        
        private HighLevelAreaVO livingPlaceAreaField;
        
        private string iDCardNumberField;
        
        private HighLevelAreaVO iDIssueAreaField;
        
        private string homeTelField;
        
        private string mobileNumberField;
        
        private DO_CODED_TEXT educationLevelField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string nationalCodeField;
        
        /// <remarks/>
        public DO_IDENTIFIER[] OtherIdentifier {
            get {
                return this.otherIdentifierField;
            }
            set {
                this.otherIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public HighLevelAreaVO BirthPlaceArea {
            get {
                return this.birthPlaceAreaField;
            }
            set {
                this.birthPlaceAreaField = value;
            }
        }
        
        /// <remarks/>
        public DO_CODED_TEXT Religion {
            get {
                return this.religionField;
            }
            set {
                this.religionField = value;
            }
        }
        
        /// <remarks/>
        public DO_CODED_TEXT MaritalStatus {
            get {
                return this.maritalStatusField;
            }
            set {
                this.maritalStatusField = value;
            }
        }
        
        /// <remarks/>
        public DO_CODED_TEXT Nationality {
            get {
                return this.nationalityField;
            }
            set {
                this.nationalityField = value;
            }
        }
        
        /// <remarks/>
        public DO_DATE BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        public DO_TIME BirthTime {
            get {
                return this.birthTimeField;
            }
            set {
                this.birthTimeField = value;
            }
        }
        
        /// <remarks/>
        public DO_CODED_TEXT BirthdateAccuracy {
            get {
                return this.birthdateAccuracyField;
            }
            set {
                this.birthdateAccuracyField = value;
            }
        }
        
        /// <remarks/>
        public string Father_FirstName {
            get {
                return this.father_FirstNameField;
            }
            set {
                this.father_FirstNameField = value;
            }
        }
        
        /// <remarks/>
        public string Father_LastName {
            get {
                return this.father_LastNameField;
            }
            set {
                this.father_LastNameField = value;
            }
        }
        
        /// <remarks/>
        public string Mother_FirstName {
            get {
                return this.mother_FirstNameField;
            }
            set {
                this.mother_FirstNameField = value;
            }
        }
        
        /// <remarks/>
        public string Mother_LastName {
            get {
                return this.mother_LastNameField;
            }
            set {
                this.mother_LastNameField = value;
            }
        }
        
        /// <remarks/>
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public DO_CODED_TEXT Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        public DO_CODED_TEXT Job {
            get {
                return this.jobField;
            }
            set {
                this.jobField = value;
            }
        }
        
        /// <remarks/>
        public string JobDescribtion {
            get {
                return this.jobDescribtionField;
            }
            set {
                this.jobDescribtionField = value;
            }
        }
        
        /// <remarks/>
        public string FullAddress {
            get {
                return this.fullAddressField;
            }
            set {
                this.fullAddressField = value;
            }
        }
        
        /// <remarks/>
        public HighLevelAreaVO LivingPlaceArea {
            get {
                return this.livingPlaceAreaField;
            }
            set {
                this.livingPlaceAreaField = value;
            }
        }
        
        /// <remarks/>
        public string IDCardNumber {
            get {
                return this.iDCardNumberField;
            }
            set {
                this.iDCardNumberField = value;
            }
        }
        
        /// <remarks/>
        public HighLevelAreaVO IDIssueArea {
            get {
                return this.iDIssueAreaField;
            }
            set {
                this.iDIssueAreaField = value;
            }
        }
        
        /// <remarks/>
        public string HomeTel {
            get {
                return this.homeTelField;
            }
            set {
                this.homeTelField = value;
            }
        }
        
        /// <remarks/>
        public string MobileNumber {
            get {
                return this.mobileNumberField;
            }
            set {
                this.mobileNumberField = value;
            }
        }
        
        /// <remarks/>
        public DO_CODED_TEXT EducationLevel {
            get {
                return this.educationLevelField;
            }
            set {
                this.educationLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NationalCode {
            get {
                return this.nationalCodeField;
            }
            set {
                this.nationalCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thrita.behdasht.gov.ir/VM/")]
    public partial class PatientBillMessageVO {
        
        private PersonInfoVO personField;
        
        private MessageIdentifierVO msgIDField;
        
        private BillPatientCompositionVO compositionField;
        
        private System.Xml.Serialization.XmlSerializerNamespaces xmlnsField;
        
        /// <remarks/>
        public PersonInfoVO Person {
            get {
                return this.personField;
            }
            set {
                this.personField = value;
            }
        }
        
        /// <remarks/>
        public MessageIdentifierVO MsgID {
            get {
                return this.msgIDField;
            }
            set {
                this.msgIDField = value;
            }
        }
        
        /// <remarks/>
        public BillPatientCompositionVO Composition {
            get {
                return this.compositionField;
            }
            set {
                this.compositionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlNamespaceDeclarationsAttribute()]
        public System.Xml.Serialization.XmlSerializerNamespaces xmlns {
            get {
                return this.xmlnsField;
            }
            set {
                this.xmlnsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SavePatientBillCompletedEventHandler(object sender, SavePatientBillCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SavePatientBillCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SavePatientBillCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultVO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultVO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SavePatientBillSecureCompletedEventHandler(object sender, SavePatientBillSecureCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SavePatientBillSecureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SavePatientBillSecureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultVO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultVO)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591