//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMOApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.4.251;Initial Catalog=ImageServer;Persist Security Info=True;" +
            "User ID=asfiya;Password=ea!as()")]
        public string ImageServerConnectionString {
            get {
                return ((string)(this["ImageServerConnectionString"]));
            }
            set {
                this["ImageServerConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.1.145;Initial Catalog=IMPHO;Persist Security Info=True;User ID" +
            "=artp;Password=506070")]
        public string IMPHOConnectionString {
            get {
                return ((string)(this["IMPHOConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ConnectToHcis {
            get {
                return ((bool)(this["ConnectToHcis"]));
            }
            set {
                this["ConnectToHcis"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.1.30;Initial Catalog=IndustrialMedicine;Persist Security Info=" +
            "True;User ID=asfiya;Password=ea!as()")]
        public string IndustrialMedicineConnectionString {
            get {
                return ((string)(this["IndustrialMedicineConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.1.145;Initial Catalog=Jamiat;Persist Security Info=True;User I" +
            "D=artp;Password=506070")]
        public string JamiatConnectionString {
            get {
                return ((string)(this["JamiatConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.1.145;Initial Catalog=HCIS;Persist Security Info=True;User ID=" +
            "artp;Password=506070")]
        public string HCISConnectionString {
            get {
                return ((string)(this["HCISConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LabelPrinterName {
            get {
                return ((string)(this["LabelPrinterName"]));
            }
            set {
                this["LabelPrinterName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PrinterName {
            get {
                return ((string)(this["PrinterName"]));
            }
            set {
                this["PrinterName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SelectedLab {
            get {
                return ((string)(this["SelectedLab"]));
            }
            set {
                this["SelectedLab"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.1.145;Initial Catalog=Hospital;Persist Security Info=True;User" +
            " ID=artp;Password=506070")]
        public string HospitalConnectionString {
            get {
                return ((string)(this["HospitalConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.30.1.145;Initial Catalog=OMO;Persist Security Info=True;User ID=a" +
            "rtp;Password=506070Data Source=172.30.1.145;Initial Catalog=OMO;Persist Security" +
            " Info=True;User ID=artp;Password=506070")]
        public string OMOConnectionString6 {
            get {
                return ((string)(this["OMOConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Data Source=172.30.1.145;Initial Catalog=OMO;Persist Security Info=True;User ID=artp;Password=506070Data Source=172.30.1.145;Initial Catalog=OMO;Persist Security Info=True;User ID=artp;Password=506070Data Source=172.30.1.145;Initial Catalog=OMO;Persist Security Info=True;User ID=artp;Password=506070Data Source=172.30.1.145;Initial Catalog=OMO;Persist Security Info=True;User ID=artp;Password=506070")]
        public string OMOConnectionString2 {
            get {
                return ((string)(this["OMOConnectionString2"]));
            }
        }
    }
}
