using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using Inventory.Data;
using Inventory.Dialogs;

namespace Inventory.Forms
{
    public partial class frmInputproducts : DevExpress.XtraEditors.XtraForm
    {
        DataClassesDataContext dc = new DataClassesDataContext();
        public frmInputproducts()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
         //   viewRequestBindingSource.DataSource = new Inventory.Data.DataClassesDataContext().View_Requests;
        }

        private void barButtonItem5_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Close();
        }


        private void frmInputproducts_Load(object sender, EventArgs e)
        {
            GetData();
        }
        private void GetData()
        {
            requestMBindingSource.DataSource = dc.RequestMs.Where(c=> (c.WarHouseORUserPMRLP == true && c.PMR == true) || (c.WarHouseORUserPMRLP == true && c.LP == true)).ToList();
            gridControl1.RefreshDataSource();
        }

        private void barButtonItem1_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            var dlg = new dlgInputproducts();
            dlg.Text = "تقاضای کالای PMR";
            dlg.dc = dc;
            dlg.boolPMR = true;
            if (dlg.ShowDialog() == DialogResult.OK)
            {
                dc.RequestMs.InsertOnSubmit(dlg.ObjectRM);
                dc.SubmitChanges();
                GetData();
            }
        }

        private void bbiEdit_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            var current =requestDBindingSource.Current as RequestD;
            var dlg = new dlgInputproducts();
            dlg.Text = "ویرایش";
            dlg.dc = dc;
            if (current == null)
            {
                MessageBox.Show("ابتدا یک مورد را انتخاب کنید", "توجه", MessageBoxButtons.OK, MessageBoxIcon.Error, MessageBoxDefaultButton.Button1, MessageBoxOptions.RightAlign | MessageBoxOptions.RtlReading);
                return;
            }
            dlg.ObjectRM = current.RequestM;


            if (dlg.ShowDialog() == DialogResult.OK)
                GetData();
            else
            {
                dc.Dispose();
                dc = new DataClassesDataContext();
                GetData();
            }
        }

        private void bbiDeleted_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
           // var row = viewRequestBindingSource.Current as View_Request;
           // dc.Dispose();
           // dc = new DataClassesDataContext();
           //var row1 = dc.RequestMs.FirstOrDefault(x => x.ID == row.ID);

           // if (MessageBox.Show("آیا از حذف اطمینان دارید ؟", "توجه", MessageBoxButtons.YesNo, MessageBoxIcon.Question, MessageBoxDefaultButton.Button1, MessageBoxOptions.RightAlign | MessageBoxOptions.RtlReading) != DialogResult.Yes)
           //     return;
           // dc.RequestMs.DeleteOnSubmit(row1);
           // var allDrow = dc.RequestDs.Where(x => x.IDRequestM == row.ID);
           // dc.RequestDs.DeleteAllOnSubmit(allDrow);
           // dc.SubmitChanges();
           // GetData();
           // gridControl1_Click(null, null);
        }

        private void gridView1_Click(object sender, EventArgs e)
        {

        }

        private void gridControl1_Click(object sender, EventArgs e)
        {
            RequestD u = new RequestD();
            var query = from P in dc.RequestDs
                        where P.IDRequestM == Int32.Parse(gridView1.GetRowCellValue(gridView1.FocusedRowHandle, "ID").ToString())
                        select P;
            gridControl2.DataSource = query;
        }

        private void barButtonItem1_ItemClick_1(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            var dlg = new dlgInputproduct();
            dlg.Text = "تقاضای کالای LP";
            dlg.dc = dc;
            if (dlg.ShowDialog() == DialogResult.OK)
            {
                dc.RequestMs.InsertOnSubmit(dlg.ObjectRM);
                dc.SubmitChanges();
                GetData();
            }
        }
    }
}