using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using Inventory.Data;
using Inventory.Dialogs;
using Inventory.Forms;
namespace Inventory.Forms
{
    public partial class frmProductParent : DevExpress.XtraEditors.XtraForm
    {
        public DataClassesDataContext dc { get; set; }
        public Product P { get; set; }
        public frmProductParent()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            productsBindingSource.DataSource = new Inventory.Data.DataClassesDataContext().Products;
        }

        private void barButtonItem2_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Close();
        }

        private void frmProductParent_Load(object sender, EventArgs e)
        {
            GetData();
        }
        private void GetData()
        {
            productBindingSource.DataSource = dc.Products.Where(c => c.GroupP == false).ToList();
            //productsBindingSource.DataSource = dc.Products.Where(c => c.Parent == null).ToList();
            lookUpEdit1.EditValue = P.ID;
            lookUpEdit1.Enabled = false;
            gridControl1.RefreshDataSource();
        }

        private void barButtonItem1_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            var par = P.ID;  /* lookUpEdit1.EditValue as Product*/

            var x = gridView1.GetSelectedRows();
            foreach (var c in x)
            {
                var a = gridView1.GetRow(c) as Product;
                a.Parent =par;

            }
            dc.SubmitChanges();
            MessageBox.Show("اطلاعات با موفقیت ثبت شد", "توجه", MessageBoxButtons.OK, MessageBoxIcon.Information, MessageBoxDefaultButton.Button1, MessageBoxOptions.RightAlign | MessageBoxOptions.RtlReading);

        }
    }
}