using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using Inventory.Data;
using Inventory.Forms;
using Inventory.Dialogs;
namespace Inventory.Dialogs
{
    public partial class dlgEditProtection : DevExpress.XtraEditors.XtraForm
    {
        public DataClassesDataContext dc { get; set; }
        public Protection PR { get; set; }
        public dlgEditProtection()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            //personsBindingSource.DataSource = new Inventory.Data.DataClassesDataContext().Persons;
            // This line of code is generated by Data Source Configuration Wizard
            lkpPerson.Properties.DataSource = new Inventory.Data.DataClassesDataContext().Persons;
            // This line of code is generated by Data Source Configuration Wizard
            lkpPerson.Properties.DataSource = new Inventory.Data.DataClassesDataContext().Persons;
            // This line of code is generated by Data Source Configuration Wizard
            lkpTahvilgirande.Properties.DataSource = new Inventory.Data.DataClassesDataContext().Persons;
            // This line of code is generated by Data Source Configuration Wizard
            lkpTahvilgirande.Properties.DataSource = new Inventory.Data.DataClassesDataContext().Persons;
            // This line of code is generated by Data Source Configuration Wizard
            personsBindingSource.DataSource = new Inventory.Data.DataClassesDataContext().Persons;
            // This line of code is generated by Data Source Configuration Wizard
            lkpPR.Properties.DataSource = new Inventory.Data.DataClassesDataContext().Products;
            // This line of code is generated by Data Source Configuration Wizard
            lkpPR.Properties.DataSource = new Inventory.Data.DataClassesDataContext().Products;
        }

        private void dlgEditProtection_Load(object sender, EventArgs e)
        {
            GetData();
        }
        private void GetData()
        {
            lkpTahvilgirande.Text = PR.Tahvilgirande;
            lkpPR.EditValue = PR.Product;
            txtIDFactor.Text = PR.IDFactor.ToString();
            lkpPerson.Text = PR.PersonName;
            lkpOrgan.EditValue = PR.OrganName;
            lkpDestination.EditValue = PR.Destination;
            txtCar.Text = PR.Car;
            txtCarNumber.Text = PR.CarNumber;
            txtDriver.Text = PR.Driver;
            txtSHP.Text = PR.DesProduct;
            txtWorker.Text = PR.Worker;
            lkpPR.Text = PR.Product.FaName;
           
           

        }

        private void btnOk_Click(object sender, EventArgs e)
        {

            Protection u = new Protection();

            //  u.Date = dtp1.Date;
            //  u.PatientCode = Int32.Parse(txtcodep.Text);
            //  u.ServiceID = (lkpsh.EditValue as Service2_Tbl).ID;
            //  u.Code = Int32.Parse(txtcode.Text);
            dc.Protections.InsertOnSubmit(u);
            MessageBox.Show("ثبت شد", "توجه", MessageBoxButtons.OK, MessageBoxIcon.Information, MessageBoxDefaultButton.Button1, MessageBoxOptions.RightAlign | MessageBoxOptions.RtlReading);
            DialogResult = DialogResult.OK;


        }
    }
}