using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using Inventory.Data;
using Inventory.Forms;
using Inventory.Dialogs;
namespace Inventory
{
    public partial class dlgTransfer : DevExpress.XtraEditors.XtraForm
    {
        public DataClassesDataContext dc { get; set; }
        public bool isEdit { get; set; }
        // public warehouse PHT { get; set; }
        public dlgTransfer()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            warehousesBindingSource.DataSource = new Inventory.Data.DataClassesDataContext().warehouses;
            // This line of code is generated by Data Source Configuration Wizard
            warehousesBindingSource1.DataSource = new Inventory.Data.DataClassesDataContext().warehouses;
        }

        private void btnNo_Click(object sender, EventArgs e)
        {
            Close();
        }

        private void dlgTransfer_Load(object sender, EventArgs e)
        {
            warehousesBindingSource.DataSource = dc.warehouses.ToList();
            warehousesBindingSource1.DataSource = dc.warehouses.ToList();
            productBindingSource.DataSource = dc.Products.ToList();
        }
        

        private void barButtonItem2_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Close();
        }

        private void btnReg_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Transfer u = new Transfer();
          //  u.warehouse = lkpOriginWarehouse.EditValue as warehouse;
         //   u.warehouse1 = lkpDestinationWarehouse.EditValue as warehouse;
            u.DocumentNumber = txtDocumentNumber.Text;
            u.DocumentDate = txtDocumentDate.Text;
            u.Description = memDescription.Text;
            dc.Transfers.InsertOnSubmit(u);
            dc.SubmitChanges();
            transferBindingSource.DataSource = dc.Transfers.ToList();
        }
    }
}