#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCISMedicalDoc.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Jamiat")]
	public partial class HCISDataContexDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPersonTbl(PersonTbl instance);
    partial void UpdatePersonTbl(PersonTbl instance);
    partial void DeletePersonTbl(PersonTbl instance);
    partial void InsertMemberPhoto(MemberPhoto instance);
    partial void UpdateMemberPhoto(MemberPhoto instance);
    partial void DeleteMemberPhoto(MemberPhoto instance);
    partial void InsertTbl_Relation(Tbl_Relation instance);
    partial void UpdateTbl_Relation(Tbl_Relation instance);
    partial void DeleteTbl_Relation(Tbl_Relation instance);
    partial void InsertTbl_ValidCenter(Tbl_ValidCenter instance);
    partial void UpdateTbl_ValidCenter(Tbl_ValidCenter instance);
    partial void DeleteTbl_ValidCenter(Tbl_ValidCenter instance);
    partial void InsertTbl_ValidCenterZone(Tbl_ValidCenterZone instance);
    partial void UpdateTbl_ValidCenterZone(Tbl_ValidCenterZone instance);
    partial void DeleteTbl_ValidCenterZone(Tbl_ValidCenterZone instance);
    partial void InsertTbl_Company(Tbl_Company instance);
    partial void UpdateTbl_Company(Tbl_Company instance);
    partial void DeleteTbl_Company(Tbl_Company instance);
    partial void InsertTbl_ManageMent(Tbl_ManageMent instance);
    partial void UpdateTbl_ManageMent(Tbl_ManageMent instance);
    partial void DeleteTbl_ManageMent(Tbl_ManageMent instance);
    partial void InsertTbl_SubCompany(Tbl_SubCompany instance);
    partial void UpdateTbl_SubCompany(Tbl_SubCompany instance);
    partial void DeleteTbl_SubCompany(Tbl_SubCompany instance);
    partial void InsertTbl_Unit(Tbl_Unit instance);
    partial void UpdateTbl_Unit(Tbl_Unit instance);
    partial void DeleteTbl_Unit(Tbl_Unit instance);
    #endregion
		
		public HCISDataContexDataContext() : 
				base(global::HCISMedicalDoc.Properties.Settings.Default.JamiatConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HCISDataContexDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HCISDataContexDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HCISDataContexDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HCISDataContexDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PersonTbl> PersonTbls
		{
			get
			{
				return this.GetTable<PersonTbl>();
			}
		}
		
		public System.Data.Linq.Table<MemberPhoto> MemberPhotos
		{
			get
			{
				return this.GetTable<MemberPhoto>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Relation> Tbl_Relations
		{
			get
			{
				return this.GetTable<Tbl_Relation>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_ValidCenter> Tbl_ValidCenters
		{
			get
			{
				return this.GetTable<Tbl_ValidCenter>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_ValidCenterZone> Tbl_ValidCenterZones
		{
			get
			{
				return this.GetTable<Tbl_ValidCenterZone>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Company> Tbl_Companies
		{
			get
			{
				return this.GetTable<Tbl_Company>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_ManageMent> Tbl_ManageMents
		{
			get
			{
				return this.GetTable<Tbl_ManageMent>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_SubCompany> Tbl_SubCompanies
		{
			get
			{
				return this.GetTable<Tbl_SubCompany>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Unit> Tbl_Units
		{
			get
			{
				return this.GetTable<Tbl_Unit>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PersonTbl")]
	public partial class PersonTbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _IDPerson;
		
		private System.Nullable<int> _IDPersonold;
		
		private int _PersonnelNo;
		
		private int _RelationOrderNo;
		
		private byte _IDRelation;
		
		private string _NationalCode;
		
		private string _Lastname;
		
		private string _Firstname;
		
		private string _FatherName;
		
		private int _Sex;
		
		private int _BirthDate;
		
		private int _IDBirthPlace;
		
		private string _IdentityNo;
		
		private int _IdentityDate;
		
		private int _IdentityPlace;
		
		private byte _IDMaritalStatus;
		
		private string _HomePhone;
		
		private string _PostCode;
		
		private string _EMail;
		
		private string _Note;
		
		private short _IDValidCenterCity;
		
		private int _IDValidCenter;
		
		private int _EntryDate;
		
		private int _ExpDate;
		
		private byte _IDEduDegree;
		
		private byte _AlertCount;
		
		private int _IDHomeCity;
		
		private string _HomeFax;
		
		private string _HomeAddress;
		
		private System.Guid _IDOpr1;
		
		private int _OprDate1;
		
		private string _OprTime1;
		
		private System.Guid _IDOpr2;
		
		private int _OprDate2;
		
		private string _OprTime2;
		
		private string _TBirthPlace;
		
		private string _TIdentityPlace;
		
		private string _TIdHomeCity;
		
		private bool _Deleted;
		
		private int _KindPeople;
		
		private System.Nullable<int> _ExpDateBook;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDPersonChanging(System.Guid value);
    partial void OnIDPersonChanged();
    partial void OnIDPersonoldChanging(System.Nullable<int> value);
    partial void OnIDPersonoldChanged();
    partial void OnPersonnelNoChanging(int value);
    partial void OnPersonnelNoChanged();
    partial void OnRelationOrderNoChanging(int value);
    partial void OnRelationOrderNoChanged();
    partial void OnIDRelationChanging(byte value);
    partial void OnIDRelationChanged();
    partial void OnNationalCodeChanging(string value);
    partial void OnNationalCodeChanged();
    partial void OnLastnameChanging(string value);
    partial void OnLastnameChanged();
    partial void OnFirstnameChanging(string value);
    partial void OnFirstnameChanged();
    partial void OnFatherNameChanging(string value);
    partial void OnFatherNameChanged();
    partial void OnSexChanging(int value);
    partial void OnSexChanged();
    partial void OnBirthDateChanging(int value);
    partial void OnBirthDateChanged();
    partial void OnIDBirthPlaceChanging(int value);
    partial void OnIDBirthPlaceChanged();
    partial void OnIdentityNoChanging(string value);
    partial void OnIdentityNoChanged();
    partial void OnIdentityDateChanging(int value);
    partial void OnIdentityDateChanged();
    partial void OnIdentityPlaceChanging(int value);
    partial void OnIdentityPlaceChanged();
    partial void OnIDMaritalStatusChanging(byte value);
    partial void OnIDMaritalStatusChanged();
    partial void OnHomePhoneChanging(string value);
    partial void OnHomePhoneChanged();
    partial void OnPostCodeChanging(string value);
    partial void OnPostCodeChanged();
    partial void OnEMailChanging(string value);
    partial void OnEMailChanged();
    partial void OnNoteChanging(string value);
    partial void OnNoteChanged();
    partial void OnIDValidCenterCityChanging(short value);
    partial void OnIDValidCenterCityChanged();
    partial void OnIDValidCenterChanging(int value);
    partial void OnIDValidCenterChanged();
    partial void OnEntryDateChanging(int value);
    partial void OnEntryDateChanged();
    partial void OnExpDateChanging(int value);
    partial void OnExpDateChanged();
    partial void OnIDEduDegreeChanging(byte value);
    partial void OnIDEduDegreeChanged();
    partial void OnAlertCountChanging(byte value);
    partial void OnAlertCountChanged();
    partial void OnIDHomeCityChanging(int value);
    partial void OnIDHomeCityChanged();
    partial void OnHomeFaxChanging(string value);
    partial void OnHomeFaxChanged();
    partial void OnHomeAddressChanging(string value);
    partial void OnHomeAddressChanged();
    partial void OnIDOpr1Changing(System.Guid value);
    partial void OnIDOpr1Changed();
    partial void OnOprDate1Changing(int value);
    partial void OnOprDate1Changed();
    partial void OnOprTime1Changing(string value);
    partial void OnOprTime1Changed();
    partial void OnIDOpr2Changing(System.Guid value);
    partial void OnIDOpr2Changed();
    partial void OnOprDate2Changing(int value);
    partial void OnOprDate2Changed();
    partial void OnOprTime2Changing(string value);
    partial void OnOprTime2Changed();
    partial void OnTBirthPlaceChanging(string value);
    partial void OnTBirthPlaceChanged();
    partial void OnTIdentityPlaceChanging(string value);
    partial void OnTIdentityPlaceChanged();
    partial void OnTIdHomeCityChanging(string value);
    partial void OnTIdHomeCityChanged();
    partial void OnDeletedChanging(bool value);
    partial void OnDeletedChanged();
    partial void OnKindPeopleChanging(int value);
    partial void OnKindPeopleChanged();
    partial void OnExpDateBookChanging(System.Nullable<int> value);
    partial void OnExpDateBookChanged();
    #endregion
		
		public PersonTbl()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPerson", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid IDPerson
		{
			get
			{
				return this._IDPerson;
			}
			set
			{
				if ((this._IDPerson != value))
				{
					this.OnIDPersonChanging(value);
					this.SendPropertyChanging();
					this._IDPerson = value;
					this.SendPropertyChanged("IDPerson");
					this.OnIDPersonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPersonold", DbType="Int")]
		public System.Nullable<int> IDPersonold
		{
			get
			{
				return this._IDPersonold;
			}
			set
			{
				if ((this._IDPersonold != value))
				{
					this.OnIDPersonoldChanging(value);
					this.SendPropertyChanging();
					this._IDPersonold = value;
					this.SendPropertyChanged("IDPersonold");
					this.OnIDPersonoldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonnelNo", DbType="Int NOT NULL")]
		public int PersonnelNo
		{
			get
			{
				return this._PersonnelNo;
			}
			set
			{
				if ((this._PersonnelNo != value))
				{
					this.OnPersonnelNoChanging(value);
					this.SendPropertyChanging();
					this._PersonnelNo = value;
					this.SendPropertyChanged("PersonnelNo");
					this.OnPersonnelNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RelationOrderNo", DbType="Int NOT NULL")]
		public int RelationOrderNo
		{
			get
			{
				return this._RelationOrderNo;
			}
			set
			{
				if ((this._RelationOrderNo != value))
				{
					this.OnRelationOrderNoChanging(value);
					this.SendPropertyChanging();
					this._RelationOrderNo = value;
					this.SendPropertyChanged("RelationOrderNo");
					this.OnRelationOrderNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDRelation", DbType="TinyInt NOT NULL")]
		public byte IDRelation
		{
			get
			{
				return this._IDRelation;
			}
			set
			{
				if ((this._IDRelation != value))
				{
					this.OnIDRelationChanging(value);
					this.SendPropertyChanging();
					this._IDRelation = value;
					this.SendPropertyChanged("IDRelation");
					this.OnIDRelationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NationalCode", DbType="NVarChar(50)")]
		public string NationalCode
		{
			get
			{
				return this._NationalCode;
			}
			set
			{
				if ((this._NationalCode != value))
				{
					this.OnNationalCodeChanging(value);
					this.SendPropertyChanging();
					this._NationalCode = value;
					this.SendPropertyChanged("NationalCode");
					this.OnNationalCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lastname", DbType="NVarChar(50)")]
		public string Lastname
		{
			get
			{
				return this._Lastname;
			}
			set
			{
				if ((this._Lastname != value))
				{
					this.OnLastnameChanging(value);
					this.SendPropertyChanging();
					this._Lastname = value;
					this.SendPropertyChanged("Lastname");
					this.OnLastnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firstname", DbType="NVarChar(50)")]
		public string Firstname
		{
			get
			{
				return this._Firstname;
			}
			set
			{
				if ((this._Firstname != value))
				{
					this.OnFirstnameChanging(value);
					this.SendPropertyChanging();
					this._Firstname = value;
					this.SendPropertyChanged("Firstname");
					this.OnFirstnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FatherName", DbType="NVarChar(80)")]
		public string FatherName
		{
			get
			{
				return this._FatherName;
			}
			set
			{
				if ((this._FatherName != value))
				{
					this.OnFatherNameChanging(value);
					this.SendPropertyChanging();
					this._FatherName = value;
					this.SendPropertyChanged("FatherName");
					this.OnFatherNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sex", DbType="Int NOT NULL")]
		public int Sex
		{
			get
			{
				return this._Sex;
			}
			set
			{
				if ((this._Sex != value))
				{
					this.OnSexChanging(value);
					this.SendPropertyChanging();
					this._Sex = value;
					this.SendPropertyChanged("Sex");
					this.OnSexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BirthDate", DbType="Int NOT NULL")]
		public int BirthDate
		{
			get
			{
				return this._BirthDate;
			}
			set
			{
				if ((this._BirthDate != value))
				{
					this.OnBirthDateChanging(value);
					this.SendPropertyChanging();
					this._BirthDate = value;
					this.SendPropertyChanged("BirthDate");
					this.OnBirthDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDBirthPlace", DbType="Int NOT NULL")]
		public int IDBirthPlace
		{
			get
			{
				return this._IDBirthPlace;
			}
			set
			{
				if ((this._IDBirthPlace != value))
				{
					this.OnIDBirthPlaceChanging(value);
					this.SendPropertyChanging();
					this._IDBirthPlace = value;
					this.SendPropertyChanged("IDBirthPlace");
					this.OnIDBirthPlaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdentityNo", DbType="NVarChar(20)")]
		public string IdentityNo
		{
			get
			{
				return this._IdentityNo;
			}
			set
			{
				if ((this._IdentityNo != value))
				{
					this.OnIdentityNoChanging(value);
					this.SendPropertyChanging();
					this._IdentityNo = value;
					this.SendPropertyChanged("IdentityNo");
					this.OnIdentityNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdentityDate", DbType="Int NOT NULL")]
		public int IdentityDate
		{
			get
			{
				return this._IdentityDate;
			}
			set
			{
				if ((this._IdentityDate != value))
				{
					this.OnIdentityDateChanging(value);
					this.SendPropertyChanging();
					this._IdentityDate = value;
					this.SendPropertyChanged("IdentityDate");
					this.OnIdentityDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdentityPlace", DbType="Int NOT NULL")]
		public int IdentityPlace
		{
			get
			{
				return this._IdentityPlace;
			}
			set
			{
				if ((this._IdentityPlace != value))
				{
					this.OnIdentityPlaceChanging(value);
					this.SendPropertyChanging();
					this._IdentityPlace = value;
					this.SendPropertyChanged("IdentityPlace");
					this.OnIdentityPlaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDMaritalStatus", DbType="TinyInt NOT NULL")]
		public byte IDMaritalStatus
		{
			get
			{
				return this._IDMaritalStatus;
			}
			set
			{
				if ((this._IDMaritalStatus != value))
				{
					this.OnIDMaritalStatusChanging(value);
					this.SendPropertyChanging();
					this._IDMaritalStatus = value;
					this.SendPropertyChanged("IDMaritalStatus");
					this.OnIDMaritalStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HomePhone", DbType="NVarChar(20)")]
		public string HomePhone
		{
			get
			{
				return this._HomePhone;
			}
			set
			{
				if ((this._HomePhone != value))
				{
					this.OnHomePhoneChanging(value);
					this.SendPropertyChanging();
					this._HomePhone = value;
					this.SendPropertyChanged("HomePhone");
					this.OnHomePhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostCode", DbType="NVarChar(20)")]
		public string PostCode
		{
			get
			{
				return this._PostCode;
			}
			set
			{
				if ((this._PostCode != value))
				{
					this.OnPostCodeChanging(value);
					this.SendPropertyChanging();
					this._PostCode = value;
					this.SendPropertyChanged("PostCode");
					this.OnPostCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMail", DbType="NVarChar(50)")]
		public string EMail
		{
			get
			{
				return this._EMail;
			}
			set
			{
				if ((this._EMail != value))
				{
					this.OnEMailChanging(value);
					this.SendPropertyChanging();
					this._EMail = value;
					this.SendPropertyChanged("EMail");
					this.OnEMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NVarChar(MAX)")]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this.OnNoteChanging(value);
					this.SendPropertyChanging();
					this._Note = value;
					this.SendPropertyChanged("Note");
					this.OnNoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDValidCenterCity", DbType="SmallInt NOT NULL")]
		public short IDValidCenterCity
		{
			get
			{
				return this._IDValidCenterCity;
			}
			set
			{
				if ((this._IDValidCenterCity != value))
				{
					this.OnIDValidCenterCityChanging(value);
					this.SendPropertyChanging();
					this._IDValidCenterCity = value;
					this.SendPropertyChanged("IDValidCenterCity");
					this.OnIDValidCenterCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDValidCenter", DbType="Int NOT NULL")]
		public int IDValidCenter
		{
			get
			{
				return this._IDValidCenter;
			}
			set
			{
				if ((this._IDValidCenter != value))
				{
					this.OnIDValidCenterChanging(value);
					this.SendPropertyChanging();
					this._IDValidCenter = value;
					this.SendPropertyChanged("IDValidCenter");
					this.OnIDValidCenterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryDate", DbType="Int NOT NULL")]
		public int EntryDate
		{
			get
			{
				return this._EntryDate;
			}
			set
			{
				if ((this._EntryDate != value))
				{
					this.OnEntryDateChanging(value);
					this.SendPropertyChanging();
					this._EntryDate = value;
					this.SendPropertyChanged("EntryDate");
					this.OnEntryDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpDate", DbType="Int NOT NULL")]
		public int ExpDate
		{
			get
			{
				return this._ExpDate;
			}
			set
			{
				if ((this._ExpDate != value))
				{
					this.OnExpDateChanging(value);
					this.SendPropertyChanging();
					this._ExpDate = value;
					this.SendPropertyChanged("ExpDate");
					this.OnExpDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDEduDegree", DbType="TinyInt NOT NULL")]
		public byte IDEduDegree
		{
			get
			{
				return this._IDEduDegree;
			}
			set
			{
				if ((this._IDEduDegree != value))
				{
					this.OnIDEduDegreeChanging(value);
					this.SendPropertyChanging();
					this._IDEduDegree = value;
					this.SendPropertyChanged("IDEduDegree");
					this.OnIDEduDegreeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlertCount", DbType="TinyInt NOT NULL")]
		public byte AlertCount
		{
			get
			{
				return this._AlertCount;
			}
			set
			{
				if ((this._AlertCount != value))
				{
					this.OnAlertCountChanging(value);
					this.SendPropertyChanging();
					this._AlertCount = value;
					this.SendPropertyChanged("AlertCount");
					this.OnAlertCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDHomeCity", DbType="Int NOT NULL")]
		public int IDHomeCity
		{
			get
			{
				return this._IDHomeCity;
			}
			set
			{
				if ((this._IDHomeCity != value))
				{
					this.OnIDHomeCityChanging(value);
					this.SendPropertyChanging();
					this._IDHomeCity = value;
					this.SendPropertyChanged("IDHomeCity");
					this.OnIDHomeCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HomeFax", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string HomeFax
		{
			get
			{
				return this._HomeFax;
			}
			set
			{
				if ((this._HomeFax != value))
				{
					this.OnHomeFaxChanging(value);
					this.SendPropertyChanging();
					this._HomeFax = value;
					this.SendPropertyChanged("HomeFax");
					this.OnHomeFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HomeAddress", DbType="NVarChar(MAX)")]
		public string HomeAddress
		{
			get
			{
				return this._HomeAddress;
			}
			set
			{
				if ((this._HomeAddress != value))
				{
					this.OnHomeAddressChanging(value);
					this.SendPropertyChanging();
					this._HomeAddress = value;
					this.SendPropertyChanged("HomeAddress");
					this.OnHomeAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDOpr1", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid IDOpr1
		{
			get
			{
				return this._IDOpr1;
			}
			set
			{
				if ((this._IDOpr1 != value))
				{
					this.OnIDOpr1Changing(value);
					this.SendPropertyChanging();
					this._IDOpr1 = value;
					this.SendPropertyChanged("IDOpr1");
					this.OnIDOpr1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OprDate1", DbType="Int NOT NULL")]
		public int OprDate1
		{
			get
			{
				return this._OprDate1;
			}
			set
			{
				if ((this._OprDate1 != value))
				{
					this.OnOprDate1Changing(value);
					this.SendPropertyChanging();
					this._OprDate1 = value;
					this.SendPropertyChanged("OprDate1");
					this.OnOprDate1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OprTime1", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string OprTime1
		{
			get
			{
				return this._OprTime1;
			}
			set
			{
				if ((this._OprTime1 != value))
				{
					this.OnOprTime1Changing(value);
					this.SendPropertyChanging();
					this._OprTime1 = value;
					this.SendPropertyChanged("OprTime1");
					this.OnOprTime1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDOpr2", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid IDOpr2
		{
			get
			{
				return this._IDOpr2;
			}
			set
			{
				if ((this._IDOpr2 != value))
				{
					this.OnIDOpr2Changing(value);
					this.SendPropertyChanging();
					this._IDOpr2 = value;
					this.SendPropertyChanged("IDOpr2");
					this.OnIDOpr2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OprDate2", DbType="Int NOT NULL")]
		public int OprDate2
		{
			get
			{
				return this._OprDate2;
			}
			set
			{
				if ((this._OprDate2 != value))
				{
					this.OnOprDate2Changing(value);
					this.SendPropertyChanging();
					this._OprDate2 = value;
					this.SendPropertyChanged("OprDate2");
					this.OnOprDate2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OprTime2", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string OprTime2
		{
			get
			{
				return this._OprTime2;
			}
			set
			{
				if ((this._OprTime2 != value))
				{
					this.OnOprTime2Changing(value);
					this.SendPropertyChanging();
					this._OprTime2 = value;
					this.SendPropertyChanged("OprTime2");
					this.OnOprTime2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TBirthPlace", DbType="NVarChar(50)")]
		public string TBirthPlace
		{
			get
			{
				return this._TBirthPlace;
			}
			set
			{
				if ((this._TBirthPlace != value))
				{
					this.OnTBirthPlaceChanging(value);
					this.SendPropertyChanging();
					this._TBirthPlace = value;
					this.SendPropertyChanged("TBirthPlace");
					this.OnTBirthPlaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIdentityPlace", DbType="NVarChar(50)")]
		public string TIdentityPlace
		{
			get
			{
				return this._TIdentityPlace;
			}
			set
			{
				if ((this._TIdentityPlace != value))
				{
					this.OnTIdentityPlaceChanging(value);
					this.SendPropertyChanging();
					this._TIdentityPlace = value;
					this.SendPropertyChanged("TIdentityPlace");
					this.OnTIdentityPlaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIdHomeCity", DbType="NVarChar(50)")]
		public string TIdHomeCity
		{
			get
			{
				return this._TIdHomeCity;
			}
			set
			{
				if ((this._TIdHomeCity != value))
				{
					this.OnTIdHomeCityChanging(value);
					this.SendPropertyChanging();
					this._TIdHomeCity = value;
					this.SendPropertyChanged("TIdHomeCity");
					this.OnTIdHomeCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted", DbType="Bit NOT NULL")]
		public bool Deleted
		{
			get
			{
				return this._Deleted;
			}
			set
			{
				if ((this._Deleted != value))
				{
					this.OnDeletedChanging(value);
					this.SendPropertyChanging();
					this._Deleted = value;
					this.SendPropertyChanged("Deleted");
					this.OnDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KindPeople", DbType="Int NOT NULL")]
		public int KindPeople
		{
			get
			{
				return this._KindPeople;
			}
			set
			{
				if ((this._KindPeople != value))
				{
					this.OnKindPeopleChanging(value);
					this.SendPropertyChanging();
					this._KindPeople = value;
					this.SendPropertyChanged("KindPeople");
					this.OnKindPeopleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpDateBook", DbType="Int")]
		public System.Nullable<int> ExpDateBook
		{
			get
			{
				return this._ExpDateBook;
			}
			set
			{
				if ((this._ExpDateBook != value))
				{
					this.OnExpDateBookChanging(value);
					this.SendPropertyChanging();
					this._ExpDateBook = value;
					this.SendPropertyChanged("ExpDateBook");
					this.OnExpDateBookChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MemberPhoto")]
	public partial class MemberPhoto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _IDPerson;
		
		private System.Data.Linq.Binary _Photo;
		
		private System.Guid _IDOpr1;
		
		private System.Guid _IDOpr2;
		
		private int _OprDate1;
		
		private int _OprDate2;
		
		private string _OprTime1;
		
		private string _OprTime2;
		
		private int _IDPersonOld;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDPersonChanging(System.Guid value);
    partial void OnIDPersonChanged();
    partial void OnPhotoChanging(System.Data.Linq.Binary value);
    partial void OnPhotoChanged();
    partial void OnIDOpr1Changing(System.Guid value);
    partial void OnIDOpr1Changed();
    partial void OnIDOpr2Changing(System.Guid value);
    partial void OnIDOpr2Changed();
    partial void OnOprDate1Changing(int value);
    partial void OnOprDate1Changed();
    partial void OnOprDate2Changing(int value);
    partial void OnOprDate2Changed();
    partial void OnOprTime1Changing(string value);
    partial void OnOprTime1Changed();
    partial void OnOprTime2Changing(string value);
    partial void OnOprTime2Changed();
    partial void OnIDPersonOldChanging(int value);
    partial void OnIDPersonOldChanged();
    #endregion
		
		public MemberPhoto()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPerson", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid IDPerson
		{
			get
			{
				return this._IDPerson;
			}
			set
			{
				if ((this._IDPerson != value))
				{
					this.OnIDPersonChanging(value);
					this.SendPropertyChanging();
					this._IDPerson = value;
					this.SendPropertyChanged("IDPerson");
					this.OnIDPersonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Photo", DbType="Image NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Photo
		{
			get
			{
				return this._Photo;
			}
			set
			{
				if ((this._Photo != value))
				{
					this.OnPhotoChanging(value);
					this.SendPropertyChanging();
					this._Photo = value;
					this.SendPropertyChanged("Photo");
					this.OnPhotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDOpr1", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid IDOpr1
		{
			get
			{
				return this._IDOpr1;
			}
			set
			{
				if ((this._IDOpr1 != value))
				{
					this.OnIDOpr1Changing(value);
					this.SendPropertyChanging();
					this._IDOpr1 = value;
					this.SendPropertyChanged("IDOpr1");
					this.OnIDOpr1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDOpr2", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid IDOpr2
		{
			get
			{
				return this._IDOpr2;
			}
			set
			{
				if ((this._IDOpr2 != value))
				{
					this.OnIDOpr2Changing(value);
					this.SendPropertyChanging();
					this._IDOpr2 = value;
					this.SendPropertyChanged("IDOpr2");
					this.OnIDOpr2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OprDate1", DbType="Int NOT NULL")]
		public int OprDate1
		{
			get
			{
				return this._OprDate1;
			}
			set
			{
				if ((this._OprDate1 != value))
				{
					this.OnOprDate1Changing(value);
					this.SendPropertyChanging();
					this._OprDate1 = value;
					this.SendPropertyChanged("OprDate1");
					this.OnOprDate1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OprDate2", DbType="Int NOT NULL")]
		public int OprDate2
		{
			get
			{
				return this._OprDate2;
			}
			set
			{
				if ((this._OprDate2 != value))
				{
					this.OnOprDate2Changing(value);
					this.SendPropertyChanging();
					this._OprDate2 = value;
					this.SendPropertyChanged("OprDate2");
					this.OnOprDate2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OprTime1", DbType="NVarChar(12) NOT NULL", CanBeNull=false)]
		public string OprTime1
		{
			get
			{
				return this._OprTime1;
			}
			set
			{
				if ((this._OprTime1 != value))
				{
					this.OnOprTime1Changing(value);
					this.SendPropertyChanging();
					this._OprTime1 = value;
					this.SendPropertyChanged("OprTime1");
					this.OnOprTime1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OprTime2", DbType="NVarChar(12) NOT NULL", CanBeNull=false)]
		public string OprTime2
		{
			get
			{
				return this._OprTime2;
			}
			set
			{
				if ((this._OprTime2 != value))
				{
					this.OnOprTime2Changing(value);
					this.SendPropertyChanging();
					this._OprTime2 = value;
					this.SendPropertyChanged("OprTime2");
					this.OnOprTime2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPersonOld", DbType="Int NOT NULL")]
		public int IDPersonOld
		{
			get
			{
				return this._IDPersonOld;
			}
			set
			{
				if ((this._IDPersonOld != value))
				{
					this.OnIDPersonOldChanging(value);
					this.SendPropertyChanging();
					this._IDPersonOld = value;
					this.SendPropertyChanged("IDPersonOld");
					this.OnIDPersonOldChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Relation")]
	public partial class Tbl_Relation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private byte _IDSJ;
		
		private string _Name;
		
		private System.Nullable<int> _Sort;
		
		private System.Nullable<int> _IDRelation;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDSJChanging(byte value);
    partial void OnIDSJChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnSortChanging(System.Nullable<int> value);
    partial void OnSortChanged();
    partial void OnIDRelationChanging(System.Nullable<int> value);
    partial void OnIDRelationChanged();
    #endregion
		
		public Tbl_Relation()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDSJ", DbType="TinyInt NOT NULL", IsPrimaryKey=true)]
		public byte IDSJ
		{
			get
			{
				return this._IDSJ;
			}
			set
			{
				if ((this._IDSJ != value))
				{
					this.OnIDSJChanging(value);
					this.SendPropertyChanging();
					this._IDSJ = value;
					this.SendPropertyChanged("IDSJ");
					this.OnIDSJChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sort", DbType="Int")]
		public System.Nullable<int> Sort
		{
			get
			{
				return this._Sort;
			}
			set
			{
				if ((this._Sort != value))
				{
					this.OnSortChanging(value);
					this.SendPropertyChanging();
					this._Sort = value;
					this.SendPropertyChanged("Sort");
					this.OnSortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDRelation", DbType="Int")]
		public System.Nullable<int> IDRelation
		{
			get
			{
				return this._IDRelation;
			}
			set
			{
				if ((this._IDRelation != value))
				{
					this.OnIDRelationChanging(value);
					this.SendPropertyChanging();
					this._IDRelation = value;
					this.SendPropertyChanged("IDRelation");
					this.OnIDRelationChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_ValidCenter")]
	public partial class Tbl_ValidCenter : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDValidCenter;
		
		private int _IDValidCenterZone;
		
		private byte _IDValidCenterType;
		
		private string _Name;
		
		private byte _Deleted;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDValidCenterChanging(int value);
    partial void OnIDValidCenterChanged();
    partial void OnIDValidCenterZoneChanging(int value);
    partial void OnIDValidCenterZoneChanged();
    partial void OnIDValidCenterTypeChanging(byte value);
    partial void OnIDValidCenterTypeChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnDeletedChanging(byte value);
    partial void OnDeletedChanged();
    #endregion
		
		public Tbl_ValidCenter()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDValidCenter", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDValidCenter
		{
			get
			{
				return this._IDValidCenter;
			}
			set
			{
				if ((this._IDValidCenter != value))
				{
					this.OnIDValidCenterChanging(value);
					this.SendPropertyChanging();
					this._IDValidCenter = value;
					this.SendPropertyChanged("IDValidCenter");
					this.OnIDValidCenterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDValidCenterZone", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDValidCenterZone
		{
			get
			{
				return this._IDValidCenterZone;
			}
			set
			{
				if ((this._IDValidCenterZone != value))
				{
					this.OnIDValidCenterZoneChanging(value);
					this.SendPropertyChanging();
					this._IDValidCenterZone = value;
					this.SendPropertyChanged("IDValidCenterZone");
					this.OnIDValidCenterZoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDValidCenterType", DbType="TinyInt NOT NULL", IsPrimaryKey=true)]
		public byte IDValidCenterType
		{
			get
			{
				return this._IDValidCenterType;
			}
			set
			{
				if ((this._IDValidCenterType != value))
				{
					this.OnIDValidCenterTypeChanging(value);
					this.SendPropertyChanging();
					this._IDValidCenterType = value;
					this.SendPropertyChanged("IDValidCenterType");
					this.OnIDValidCenterTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(70) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted", DbType="TinyInt NOT NULL")]
		public byte Deleted
		{
			get
			{
				return this._Deleted;
			}
			set
			{
				if ((this._Deleted != value))
				{
					this.OnDeletedChanging(value);
					this.SendPropertyChanging();
					this._Deleted = value;
					this.SendPropertyChanged("Deleted");
					this.OnDeletedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_ValidCenterZone")]
	public partial class Tbl_ValidCenterZone : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDValidCenterZone;
		
		private string _Name;
		
		private bool _Deleted;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDValidCenterZoneChanging(int value);
    partial void OnIDValidCenterZoneChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnDeletedChanging(bool value);
    partial void OnDeletedChanged();
    #endregion
		
		public Tbl_ValidCenterZone()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDValidCenterZone", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDValidCenterZone
		{
			get
			{
				return this._IDValidCenterZone;
			}
			set
			{
				if ((this._IDValidCenterZone != value))
				{
					this.OnIDValidCenterZoneChanging(value);
					this.SendPropertyChanging();
					this._IDValidCenterZone = value;
					this.SendPropertyChanged("IDValidCenterZone");
					this.OnIDValidCenterZoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(70) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted", DbType="Bit NOT NULL")]
		public bool Deleted
		{
			get
			{
				return this._Deleted;
			}
			set
			{
				if ((this._Deleted != value))
				{
					this.OnDeletedChanging(value);
					this.SendPropertyChanging();
					this._Deleted = value;
					this.SendPropertyChanged("Deleted");
					this.OnDeletedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Company")]
	public partial class Tbl_Company : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDCo;
		
		private int _IDMg;
		
		private string _Name;
		
		private System.Nullable<byte> _IDManagement;
		
		private System.Nullable<short> _IDCompany;
		
		private int _id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDCoChanging(int value);
    partial void OnIDCoChanged();
    partial void OnIDMgChanging(int value);
    partial void OnIDMgChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnIDManagementChanging(System.Nullable<byte> value);
    partial void OnIDManagementChanged();
    partial void OnIDCompanyChanging(System.Nullable<short> value);
    partial void OnIDCompanyChanged();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    #endregion
		
		public Tbl_Company()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDCo
		{
			get
			{
				return this._IDCo;
			}
			set
			{
				if ((this._IDCo != value))
				{
					this.OnIDCoChanging(value);
					this.SendPropertyChanging();
					this._IDCo = value;
					this.SendPropertyChanged("IDCo");
					this.OnIDCoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDMg", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDMg
		{
			get
			{
				return this._IDMg;
			}
			set
			{
				if ((this._IDMg != value))
				{
					this.OnIDMgChanging(value);
					this.SendPropertyChanging();
					this._IDMg = value;
					this.SendPropertyChanged("IDMg");
					this.OnIDMgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDManagement", DbType="TinyInt")]
		public System.Nullable<byte> IDManagement
		{
			get
			{
				return this._IDManagement;
			}
			set
			{
				if ((this._IDManagement != value))
				{
					this.OnIDManagementChanging(value);
					this.SendPropertyChanging();
					this._IDManagement = value;
					this.SendPropertyChanged("IDManagement");
					this.OnIDManagementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCompany", DbType="SmallInt")]
		public System.Nullable<short> IDCompany
		{
			get
			{
				return this._IDCompany;
			}
			set
			{
				if ((this._IDCompany != value))
				{
					this.OnIDCompanyChanging(value);
					this.SendPropertyChanging();
					this._IDCompany = value;
					this.SendPropertyChanged("IDCompany");
					this.OnIDCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_ManageMent")]
	public partial class Tbl_ManageMent : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDCo;
		
		private string _Name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDCoChanging(int value);
    partial void OnIDCoChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public Tbl_ManageMent()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDCo
		{
			get
			{
				return this._IDCo;
			}
			set
			{
				if ((this._IDCo != value))
				{
					this.OnIDCoChanging(value);
					this.SendPropertyChanging();
					this._IDCo = value;
					this.SendPropertyChanged("IDCo");
					this.OnIDCoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_SubCompany")]
	public partial class Tbl_SubCompany : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDco;
		
		private int _IDMg;
		
		private int _IDOrgan;
		
		private string _Name;
		
		private System.Nullable<byte> _IDManagement;
		
		private System.Nullable<short> _IDCompany;
		
		private System.Nullable<short> _IDSubCompany;
		
		private short _id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDcoChanging(int value);
    partial void OnIDcoChanged();
    partial void OnIDMgChanging(int value);
    partial void OnIDMgChanged();
    partial void OnIDOrganChanging(int value);
    partial void OnIDOrganChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnIDManagementChanging(System.Nullable<byte> value);
    partial void OnIDManagementChanged();
    partial void OnIDCompanyChanging(System.Nullable<short> value);
    partial void OnIDCompanyChanged();
    partial void OnIDSubCompanyChanging(System.Nullable<short> value);
    partial void OnIDSubCompanyChanged();
    partial void OnidChanging(short value);
    partial void OnidChanged();
    #endregion
		
		public Tbl_SubCompany()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDco", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDco
		{
			get
			{
				return this._IDco;
			}
			set
			{
				if ((this._IDco != value))
				{
					this.OnIDcoChanging(value);
					this.SendPropertyChanging();
					this._IDco = value;
					this.SendPropertyChanged("IDco");
					this.OnIDcoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDMg", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDMg
		{
			get
			{
				return this._IDMg;
			}
			set
			{
				if ((this._IDMg != value))
				{
					this.OnIDMgChanging(value);
					this.SendPropertyChanging();
					this._IDMg = value;
					this.SendPropertyChanged("IDMg");
					this.OnIDMgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDOrgan", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDOrgan
		{
			get
			{
				return this._IDOrgan;
			}
			set
			{
				if ((this._IDOrgan != value))
				{
					this.OnIDOrganChanging(value);
					this.SendPropertyChanging();
					this._IDOrgan = value;
					this.SendPropertyChanged("IDOrgan");
					this.OnIDOrganChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDManagement", DbType="TinyInt")]
		public System.Nullable<byte> IDManagement
		{
			get
			{
				return this._IDManagement;
			}
			set
			{
				if ((this._IDManagement != value))
				{
					this.OnIDManagementChanging(value);
					this.SendPropertyChanging();
					this._IDManagement = value;
					this.SendPropertyChanged("IDManagement");
					this.OnIDManagementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCompany", DbType="SmallInt")]
		public System.Nullable<short> IDCompany
		{
			get
			{
				return this._IDCompany;
			}
			set
			{
				if ((this._IDCompany != value))
				{
					this.OnIDCompanyChanging(value);
					this.SendPropertyChanging();
					this._IDCompany = value;
					this.SendPropertyChanged("IDCompany");
					this.OnIDCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDSubCompany", DbType="SmallInt")]
		public System.Nullable<short> IDSubCompany
		{
			get
			{
				return this._IDSubCompany;
			}
			set
			{
				if ((this._IDSubCompany != value))
				{
					this.OnIDSubCompanyChanging(value);
					this.SendPropertyChanging();
					this._IDSubCompany = value;
					this.SendPropertyChanged("IDSubCompany");
					this.OnIDSubCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="SmallInt NOT NULL IDENTITY", IsDbGenerated=true)]
		public short id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Unit")]
	public partial class Tbl_Unit : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDco;
		
		private int _IDMg;
		
		private int _IDOrgan;
		
		private int _IDUnit;
		
		private string _Name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDcoChanging(int value);
    partial void OnIDcoChanged();
    partial void OnIDMgChanging(int value);
    partial void OnIDMgChanged();
    partial void OnIDOrganChanging(int value);
    partial void OnIDOrganChanged();
    partial void OnIDUnitChanging(int value);
    partial void OnIDUnitChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public Tbl_Unit()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDco", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDco
		{
			get
			{
				return this._IDco;
			}
			set
			{
				if ((this._IDco != value))
				{
					this.OnIDcoChanging(value);
					this.SendPropertyChanging();
					this._IDco = value;
					this.SendPropertyChanged("IDco");
					this.OnIDcoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDMg", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDMg
		{
			get
			{
				return this._IDMg;
			}
			set
			{
				if ((this._IDMg != value))
				{
					this.OnIDMgChanging(value);
					this.SendPropertyChanging();
					this._IDMg = value;
					this.SendPropertyChanged("IDMg");
					this.OnIDMgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDOrgan", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDOrgan
		{
			get
			{
				return this._IDOrgan;
			}
			set
			{
				if ((this._IDOrgan != value))
				{
					this.OnIDOrganChanging(value);
					this.SendPropertyChanging();
					this._IDOrgan = value;
					this.SendPropertyChanged("IDOrgan");
					this.OnIDOrganChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDUnit", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDUnit
		{
			get
			{
				return this._IDUnit;
			}
			set
			{
				if ((this._IDUnit != value))
				{
					this.OnIDUnitChanging(value);
					this.SendPropertyChanging();
					this._IDUnit = value;
					this.SendPropertyChanged("IDUnit");
					this.OnIDUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
