using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;

namespace HCISInsurance.Forms
{
    public partial class frmPivot : DevExpress.XtraEditors.XtraForm
    {
        public frmPivot()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            viewTariffCompletesBindingSource.DataSource = new HCISInsurance.Data.HCISClassesDataContext().ViewTariffCompletes;
        }

        private void btnClose_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Close();
        }
    }
}